import { useEffect, useState } from "react";
import API from "../services/api";
import { AdminLayout } from "./AdminDashboard";

export function AdvancedAnalyticsPage() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { API.get("/news/analytics").then((response) => setData(response.data)).catch(() => setError("Analytics could not be loaded.")); }, []);
  const total = (data?.totalNews || 0) + (data?.totalPosts || 0);
  return <AdminLayout pageEyebrow="Advanced Analytics" pageTitle="Advanced Analytics"><p className="max-w-2xl text-slate-600">Live content performance and category distribution from your NewsStore24 database.</p>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Content", total],["Published", data?.published ?? "—"],["Drafts", data?.drafts ?? "—"],["Views", data ? Number(data.totalViews || 0).toLocaleString("en-IN") : "—"]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-black text-slate-950">{value}</p></div>)}</div><section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Category performance</h2><div className="mt-5 space-y-3">{(data?.categories || []).map((item) => <div key={item._id} className="flex items-center gap-3"><span className="w-28 text-sm font-semibold capitalize text-slate-700">{item._id || "Other"}</span><div className="h-3 flex-1 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-red-600" style={{ width: `${total ? Math.max(4, (item.count / total) * 100) : 0}%` }} /></div><span className="w-8 text-right text-sm font-bold">{item.count}</span></div>)}</div></section></AdminLayout>;
}

export function MonetizationPage() {
  const [monthlyViews, setMonthlyViews] = useState(100000);
  const [rpm, setRpm] = useState(3);
  const estimated = (Number(monthlyViews) / 1000) * Number(rpm);
  return <AdminLayout pageEyebrow="Monetization" pageTitle="Monetization"><p className="max-w-2xl text-slate-600">Plan advertising and sponsorship revenue using transparent estimates. Payment integration can be connected after an ad provider is configured.</p><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_0.8fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Revenue estimator</h2><label className="mt-6 block text-sm font-semibold">Monthly page views<input type="number" min="0" value={monthlyViews} onChange={(event) => setMonthlyViews(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 p-3" /></label><label className="mt-4 block text-sm font-semibold">Estimated RPM (USD)<input type="number" min="0" step="0.1" value={rpm} onChange={(event) => setRpm(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 p-3" /></label></section><section className="rounded-3xl bg-slate-950 p-6 text-white shadow-sm"><p className="text-sm text-slate-300">Estimated monthly ad revenue</p><p className="mt-3 text-4xl font-black">${estimated.toFixed(2)}</p><p className="mt-4 text-sm text-slate-400">Estimate only. Actual revenue depends on fill rate, geography, ad network, and traffic quality.</p></section></div><section className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-black text-amber-950">Next monetization connections</h2><p className="mt-2 text-sm leading-6 text-amber-900">AdSense placement, direct sponsorship slots, newsletter sponsorship, and affiliate tracking can be configured here once provider IDs are available.</p></section></AdminLayout>;
}

export function AdvancedAIPage() {
  const [text, setText] = useState("");
  const [result, setResult] = useState(null);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const generate = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await API.post("/ai/summary", { text }); setResult(response.data); } catch (requestError) { setError(requestError.response?.data?.message || "AI generation failed."); } finally { setLoading(false); } };
  const ask = async (event) => { event.preventDefault(); try { const response = await API.post("/ai/chat", { title: "NewsStore24 AI workspace", content: result?.summary || text, question }); setAnswer(response.data.answer); } catch { setAnswer("AI answer could not be generated."); } };
  return <AdminLayout pageEyebrow="Advanced AI" pageTitle="Advanced AI"><p className="max-w-2xl text-slate-600">Generate structured summaries, key points, facts, SEO fields, and ask questions about a draft before publishing.</p><div className="mt-6 grid gap-6 xl:grid-cols-2"><form onSubmit={generate} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><label className="text-sm font-semibold">Article text<textarea required value={text} onChange={(event) => setText(event.target.value)} rows="12" placeholder="Title: ...\nDescription: ...\nContent: ..." className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 p-3" /></label><button disabled={loading} className="mt-4 rounded-xl bg-red-600 px-5 py-3 font-semibold text-white disabled:opacity-60">{loading ? "Generating..." : "Generate AI package"}</button>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</form><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Generated output</h2>{result ? <div className="mt-4 space-y-4 text-sm"><p><b>Summary:</b> {result.summary}</p><p><b>SEO:</b> {result.aiResponse?.seoTitle} | {result.aiResponse?.metaDescription}</p><p><b>Tags:</b> {(result.aiResponse?.keywords || []).join(", ")}</p></div> : <p className="mt-4 text-slate-500">Generated AI output will appear here.</p>}<form onSubmit={ask} className="mt-6 border-t border-slate-200 pt-5"><input required value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about this draft" className="w-full rounded-xl border border-slate-200 p-3" /><button className="mt-3 rounded-xl border border-slate-300 px-4 py-2 font-semibold">Ask AI</button>{answer && <p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">{answer}</p>}</form></section></div></AdminLayout>;
}
